Praktican zadatak SQL - Bosko Jevtic/Models/Proizvod.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktican_zadatak_SQL___Bosko_Jevtic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvod
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Kategorija { get; set; }
        public string Proizvodjac { get; set; }
        public string Dobavljac { get; set; }
        public Nullable<int> Cena { get; set; }
    }
}

Praktican zadatak SQL - Bosko Jevtic/Models/ProizvodViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Praktican_zadatak_SQL___Bosko_Jevtic.Models
{
    public class ProizvodViewModel
    {
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Kategorija { get; set; }
        public string Proizvodjac { get; set; }
        public string Dobavljac { get; set; }
        public Nullable<int> Cena { get; set; }
    }
}

Praktican zadatak SQL - Bosko Jevtic/Controllers/ProizvodController.cs
using Praktican_zadatak_SQL___Bosko_Jevtic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Praktican_zadatak_SQL___Bosko_Jevtic.Controllers
{
    public class ProizvodController : Controller
    {
        // GET: Proizvod
        public ActionResult Index()
        {
            PomocnoDBEntities db = new PomocnoDBEntities();
            List<Proizvod> proizvodList = db.Proizvods.ToList();
            ProizvodViewModel proizvodVM = new ProizvodViewModel();
            List<ProizvodViewModel> proizvodVMList = proizvodList.Select(x => new ProizvodViewModel {
                Id = x.Id,
                Naziv = x.Naziv,
                Opis = x.Opis,
                Kategorija = x.Kategorija,
                Proizvodjac =x.Proizvodjac,
                Dobavljac =x.Dobavljac,
                Cena =x.Cena }).ToList();
            return View(proizvodVMList);
        }

        public ActionResult CreateRec(ProizvodViewModel model)
        {
            if (model.Naziv != null && model.Opis != null && model.Kategorija != null && model.Proizvodjac != null && model.Dobavljac != null)
            {
                PomocnoDBEntities db = new PomocnoDBEntities();
                Proizvod element = new Proizvod();
                element.Naziv = model.Naziv;
                element.Opis = model.Opis;
                element.Kategorija = model.Kategorija;
                element.Proizvodjac = model.Proizvodjac;
                element.Dobavljac = model.Dobavljac;
                element.Cena = model.Cena;

                db.Proizvods.Add(element);
                db.SaveChanges();
            }
            return View();
        }

        public ActionResult DeleteRec(ProizvodViewModel model)
        {
            if (model.Id != 0)
            {
                PomocnoDBEntities db = new PomocnoDBEntities();
                Proizvod element = new Proizvod();
                element = db.Proizvods.Find(model.Id);
                if (element != null)
                {
                    db.Proizvods.Remove(element);
                    db.SaveChanges();
                }
            }
            return View();
        }

        public ActionResult UpdateRec(ProizvodViewModel model)
        {
            if (model.Id != 0)
            {
                PomocnoDBEntities db = new PomocnoDBEntities();
                Proizvod element = new Proizvod();
                element = db.Proizvods.Find(model.Id);
                if (element != null)
                {
                    db.Proizvods.Remove(element);

                    Proizvod elementNew = new Proizvod();
                    elementNew.Naziv = model.Naziv;
                    elementNew.Opis = model.Opis;
                    elementNew.Kategorija = model.Kategorija;
                    elementNew.Proizvodjac = model.Proizvodjac;
                    elementNew.Dobavljac = model.Dobavljac;
                    elementNew.Cena = model.Cena;
                    db.Proizvods.Add(elementNew);

                    db.SaveChanges();
                }
            }
            return View();
        }


    }
}

Praktican zadatak SQL - Bosko Jevtic/Views/Proizvod/CreateRec.cshtml
@model  Praktican_zadatak_SQL___Bosko_Jevtic.Models.ProizvodViewModel


@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="container" style="width:100%;margin-top:2%">

    @using (Html.BeginForm("CreateRec", "Proizvod", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", @placeholder = "Naziv" })
        @Html.TextBoxFor(model => model.Opis, new { @class = "form-control", @placeholder = "Opis" })
        @Html.TextBoxFor(model => model.Kategorija, new { @class = "form-control", @placeholder = "Kategorija" })
        @Html.TextBoxFor(model => model.Proizvodjac, new { @class = "form-control", @placeholder = "Proizvodjac" })
        @Html.TextBoxFor(model => model.Dobavljac, new { @class = "form-control", @placeholder = "Dobavljac" })
        @Html.TextBoxFor(model => model.Cena, new { @type = "number", @min = "1", @placeholder = "Cena" })

        <input type="submit" value="submit" class="btn btn-block btn-primary" />
    }

</div>

<div>
    @Html.ActionLink("Vrati se nazad", "Index")
</div>

Praktican zadatak SQL - Bosko Jevtic/Views/Proizvod/DeleteRec.cshtml
@model  Praktican_zadatak_SQL___Bosko_Jevtic.Models.ProizvodViewModel


@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="container" style="width:100%;margin-top:2%">

    @using (Html.BeginForm("DeleteRec", "Proizvod", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.Id, new { @type = "number", @min = "1", @placeholder = "Id" })

        <input type="submit" value="submit" class="btn btn-block btn-primary" />
    }

</div>

<div>
    @Html.ActionLink("Vrati se nazad", "Index")
</div>

Praktican zadatak SQL - Bosko Jevtic/Views/Proizvod/Index.cshtml
@model  IEnumerable<Praktican_zadatak_SQL___Bosko_Jevtic.Models.ProizvodViewModel>


@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="container" style="width:100%;margin-top:2%">
    @if (Model != null)
    {
        <table class="table table-striped">
            <tr>
                <th>Id</th>
                <th>Naziv</th>
                <th>Opis</th>
                <th>Kategorija</th>
                <th>Proizvodjac</th>
                <th>Dobavljac</th>
                <th>Cena</th>
            </tr>

            <tbody>
                @foreach (var element in Model)
                {
                    <tr>
                        <th>@element.Id</th>
                        <th>@element.Naziv</th>
                        <th>@element.Opis</th>
                        <th>@element.Kategorija</th>
                        <th>@element.Proizvodjac</th>
                        <th>@element.Dobavljac</th>
                        <th>@element.Cena</th>
                    </tr>
                }
            </tbody>
        </table>
    }
 
    <div>
        @Html.ActionLink("Dodaj", "CreateRec")
        @Html.ActionLink("Brisi", "DeleteRec")
        @Html.ActionLink("Menjaj", "UpdateRec")
    </div>
           
</div>



Praktican zadatak SQL - Bosko Jevtic/Views/Proizvod/UpdateRec.cshtml
@model  Praktican_zadatak_SQL___Bosko_Jevtic.Models.ProizvodViewModel


@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div class="container" style="width:100%;margin-top:2%">

    @using (Html.BeginForm("UpdateRec", "Proizvod", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.Id, new { @type = "number", @min = "1", @placeholder = "Id" })
        @Html.TextBoxFor(model => model.Naziv, new { @class = "form-control", @placeholder = "Naziv" })
        @Html.TextBoxFor(model => model.Opis, new { @class = "form-control", @placeholder = "Opis" })
        @Html.TextBoxFor(model => model.Kategorija, new { @class = "form-control", @placeholder = "Kategorija" })
        @Html.TextBoxFor(model => model.Proizvodjac, new { @class = "form-control", @placeholder = "Proizvodjac" })
        @Html.TextBoxFor(model => model.Dobavljac, new { @class = "form-control", @placeholder = "Dobavljac" })
        @Html.TextBoxFor(model => model.Cena, new { @type = "number", @min = "1", @placeholder = "Cena" })

        <input type="submit" value="submit" class="btn btn-block btn-primary" />
    }

</div>

<div>
    @Html.ActionLink("Vrati se nazad", "Index")
</div>